repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        files: ^backend/
    -   id: end-of-file-fixer
        files: ^backend/
    -   id: check-yaml
        files: ^backend/
    -   id: check-added-large-files
        files: ^backend/

-   repo: https://github.com/ambv/black
    rev: 22.12.0  
    hooks:
    -   id: black
        files: ^backend/
        language_version: python3

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        files: ^backend/

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        files: ^backend/
        args: [--config=backend/.flake8]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  
    hooks:
    -   id: mypy
        files: ^backend/

# -   repo: local
#     hooks:
#     -   id: pytest
#         name: pytest
#         entry: sh -c 'cd backend && poetry run pytest'
#         language: system
#         types: [python]