version: '3.8'
services:
  redis:
    image: "redis:alpine"
    platform: linux/amd64

  db:
    image: "mysql:5.7"
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: 'assetmanagement'
      MYSQL_ROOT_PASSWORD: 'qwerasdf12'
    volumes:
      - db-data:/var/lib/mysql

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - db
      - redis
    volumes:
      - .:/code

  stock_hourly:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: ["python", "-m", "data.naver.stock_hourly", "korea"]
    depends_on:
      - fastapi
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    volumes:
      - .:/code

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    environment:
      VERBOSE_LOGGING: "true"
    depends_on:
      - redis

volumes:
  db-data:
  redisinsight-data:
